name: "🤖 gdbuild: Run 'target' command"
description: "Runs the 'gdbuild' target command."

inputs:
  target:
    description: "The name of the target to export."
    required: true
  platform:
    description: "The platform to build the export template for."
    required: true
  profile:
    description: "The template profile to build."
    required: false
  features:
    description: "A space-, comma- or new line-separated list of features to enable."
    required: false
    default: ""
  out-dir:
    description: "The directory in which to place the exported artifacts."
    required: false
    default: "dist"
  project-dir:
    description: "The path to the game project directory."
    required: false
    default: "."
  manifest-path:
    description: "A specific 'gdbuild' manifest filename (relative to 'project-dir')."
    required: false
  verbose:
    description: "Whether to run the command with increased log output."
    required: false
    default: false
  skip-cache:
    description: "Whether to skip caching the target export."
    required: false
    default: false
  execute:
    description: "Whether to actually run the command."
    required: false
    default: true

outputs:
  cache-hit:
    description: "Whether a cached target was found."
    value: ${{ steps.cache-exports.outputs.cache-hit }}
  command:
    description: "The 'gdbuild' command to export the target."
    value: ${{ steps.run.outputs.command }}
  hash:
    description: "The unique hash of the target export."
    value: ${{ steps.config.outputs.target-hash }}

runs:
  using: "composite"
  steps:
    - name: Build target args
      id: config
      shell: bash
      run: |
        FEATURES=()
        for f in $(printf "${{ inputs.features }}" | tr -s ', ' \\n); do
          FEATURES+=(--feature $f)
        done

        TARGET_ARGS=$(
          echo target \
            ${FEATURES[@]} \
            --platform ${{ inputs.platform }} \
            --project ${{ inputs.project-dir }} \
            $([[ '${{ inputs.verbose }}' != 'false' ]] && echo '--verbose') \
            $([[ '${{ inputs.profile }}' == 'debug' ]] && echo '--debug') \
            $([[ '${{ inputs.profile }}' == 'release' ]] && echo '--release') \
            $([[ '${{ inputs.profile }}' == 'release_debug' ]] && echo '--release_debug') \
            $([[ '${{ inputs.manifest-path }}' != '' ]] && echo --config '${{ inputs.project-dir }}/${{ inputs.manifest-path }}')
        )

        echo args="$TARGET_ARGS" >> "$GITHUB_OUTPUT"

    - name: Determine unique target hash
      id: print-hash
      shell: bash
      run: echo value="$(echo "${{ steps.config.outputs.args }} --print-hash  ${{ inputs.target }}" | xargs gdbuild)" >> "$GITHUB_OUTPUT"

    - name: Cache the 'gdbuild' store's export artifact directory
      id: cache-exports
      if: inputs.skip-cache != 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.GDBUILD_HOME }}/exports
        key: exports-${{ runner.os }}-${{ steps.print-hash.outputs.value }}

    - name: Execute the export command
      id: run
      shell: bash
      run: |
        CMD="${{ steps.config.outputs.args }} --out ${{ inputs.out-dir }} ${{ inputs.target }}"

        echo command="gdbuild $(echo "$CMD" | xargs)" >> "$GITHUB_OUTPUT"

        if [[ "${{ inputs.execute }}" == 'true' ]]; then
          echo "$CMD" | xargs gdbuild
        fi
