before:
  hooks:
    - go mod tidy

# ----------------------------------- Build ---------------------------------- #

builds:
  - id: gdbuild
    main: ./cmd/gdbuild
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
      - GODEBUG=tarinsecurepath=0,zipinsecurepath=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

# --------------------------------- Release --------------------------------- #

archives:
  - id: gdbuild
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      # Include the 'gdbuild-shim' binary for the appropriate build target
      - gdbuild-shim_{{ .Os }}_{{ .Arch }}/*
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-

      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-

      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  disable: true

checksum:
  name_template: checksums.txt
  ids:
    - gdbuild
